title: Valores Globales
menu:
  img: /u/base/logo-x.svg
  items:
  - url: /
    label: Inicio
  - url: /#proyecto
    label: El Proyecto
  - url: /#directorio
    label: Directorio
  - url: /#te-interesa
    label: ¿Te Interesa?
  - url: /#encuentros
    label: Encuentros
  - url: /#galeria
    label: Galería
  - url: /#redes
    label: Redes
  - url: /#contacto
    label: Contacto
  - url: /alta/
    label: Hazte Soci@
    btn: alt
footer:
  color: such
  div: brush
  dots:
  - url: https://chat.whatsapp.com/DPbPJBRTk8pChDJBJP6q22
    icon: brand:whatsapp
  - url: https://t.me/lagrantribunomada
    icon: brand:telegram
  - url: https://www.instagram.com/lagrantribunomada/
  - url: https://www.youtube.com/@lagrantribunomada
